version: 0.2 
 
#env: 
  #variables: 
     # key: "value" 
     # key: "value" 
  #parameter-store: 
     # key: "value" 
     # key: "value" 
 
phases: 
  install:
    runtime-versions:
        docker: 18
  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    # update the following line with your own region
    - $(aws ecr get-login --no-include-email --region us-east-1)
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    # update the following line with the name of your own ECR repository
    - docker build -t webapp .
    # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
    - docker tag webapp:latest 919244020071.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker push 919244020071.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
#artifacts: 
    # - location 
    # - location 
  #discard-paths: yes 
  #base-directory: location 
#cache: 
  #paths: 
    # - paths 
 
